default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: Black code formatter
-   repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        name: Pylint code linter
        files: ^nest/
        additional_dependencies: [matplotlib, numpy, tqdm, aiocoap]
