# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019-2021 NITK Surathkal

version: '3.4'
services:
  test:
    build:
      cache_from:
        - $CONTAINER_TEST_DEFAULT_IMAGE
      context: .
      target: test
    image: $CONTAINER_TEST_CI_IMAGE
  dev:
    build:
      cache_from:
        - $CONTAINER_TEST_DEFAULT_IMAGE
      context: .
      target: dev
    image: $CONTAINER_DEV_IMAGE
